export const skills = [
  { value: "HTML", label: "HTML" },
  { value: "CSS", label: "CSS" },
  { value: "Javascript", label: "Javascript" },
  { value: "React", label: "React" },
  { value: "Angular", label: "Angular" },
  { value: "jQuery", label: "jQuery" },
  { value: "NodeJS", label: "NodeJS" },
  { value: "Python", label: "Python" },
  { value: "PHP", label: "PHP" },
  { value: "Ruby On Rails", label: "Ruby On Rails" },
  { value: "SQL", label: "SQL" },
  { value: "BackboneJS", label: "BackboneJS" },
  { value: "Web Design", label: "Web Design" },
  { value: "Project management", label: "Project management" },
  { value: "Git", label: "Git" },
  { value: "Docker", label: "Docker" },
  { value: "AWS Lambda", label: "AWS Lambda" },
  { value: "Firebase", label: "Firebase" },
];
