export const ADD_ACCOUNT_DATA = "ADD_ACCOUNT_DATA";
export const ADD_ACCOUNT_DATA_SUCCESS = "ADD_ACCOUNT_DATA_SUCCESS";

export const ADD_PROFILE_DATA = "ADD_PROFILE_DATA";
export const ADD_CONTACTS_DATA = "ADD_CONTACTS_DATA";
export const ADD_CAPABILITIES_DATA = "ADD_CAPABILITIES_DATA";
